apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: abishik-us-tls
spec:
  secretName: abishik-us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: abishik.us
  dnsNames:
    - abishik.us
    - www.abishik.us
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - abishik.us
          - www.abishik.us